spring:
  session:
  store-type: jdbc
  jdbc.initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  properties:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      id:
        new_generator_mappings: false
      format_sql: true
      cache:
        use_second_level_cache: false
        use_query_cache: false
      generate_statistics: true
    open-in-view: false

logging:
  level:
    org.springframework.cache: TRACE

server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include:
          - "info"
          - "health"
          - "httptrace"
          - "prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}