primary:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://aiss-local-db:3306/inspire12_api?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Seoul
    username: paige
    password: paige12#
    hikari:
      connection-test-query: SELECT 1 FROM DUAL

server:
  port: 8070

spring:
  jpa:
#    hibernate:
#      ddl-auto: validate
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        format_sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: true
    open-in-view: false

  session:
  store-type: jdbc
  jdbc.initialize-schema: always
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.cache: TRACE

management:
  endpoints:
    web:
      exposure:
        include:
          - "info"
          - "health"
          - "httptrace"
          - "prometheus"

  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}