version: "3"

services:
  zookeeper:
    image: debezium/zookeeper:1.2
    restart: always
    ports:
      - 2181:2181
      - 2182:2182
      - 2183:2183

  kafka:
    image: debezium/kafka:1.2
    #    restart: always
    ports:
      - 9092:9092
      - 9093:9092
      - 9094:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper:2182,zookeeper:2183
      - HOST_NAME=kafka
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    depends_on:
      - zookeeper

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181,zookeeper:2888,zookeeper:3888"
      APPLICATION_SECRET: "random-secret"

  connect:
    image: debezium/connect:1.2
    #    restart: always
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  ksql-server:
    image: confluentinc/cp-ksqldb-server:7.0.0
    hostname: ksql-server
    depends_on:
      - kafka
      - connect
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_HOST_NAME: ksql-server
      KSQL_APPLICATION_ID: "cp-all-in-one"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0

  ksql-cli:
    image: confluentinc/cp-ksqldb-cli:7.0.0
    depends_on:
      - kafka
      - connect
      - ksql-server
    entrypoint: /bin/sh
    tty: true
